### PR TITLE
fpu: :arrow_up: Update FPU version

### PR DESCRIPTION
**Pull request by niwis**
Required by #1024.

Update the FPU version used by CVA6.

@mp-17 could you double-check this PR before undrafting? Also, @JeanRochCoulon had a question regarding this change in #1024:

> The FPU was previously v0.6.2
> The plan was to switch FPU version on June 2023 to point on the FPU version verified by Dolphin team. Has the vector FPU modification been integrated in pulp-platform project to allow to get the Dolphin team improvements?

Let's continue this discussion here.

### CODE REVIEW

**Comment by zarubaf** [comment]
Yeah, wanted to ask that as well. Can we merge the `vec` branch into a proper release on the `fpnew`, or are there large changes that would block merging?

**Comment by mp-17** [comment]
Hello guys! Yes, we can try to merge this in `fpnew`, but I don't know if everything would agree. 

The modifications include:
1) Fix bug triggered by vectorial divisions/sqrts.
2) Add support for RISC-V-compliant classify when the width of the vectori elements is at least 10 bits.
3) Add a `mask` input signal to mask the exceptions from inactive SIMD elements.
4) Add support for rounding toward odd.

Regarding @JeanRochCoulon question, I am not sure I got it completely. From my understanding, Dolphin's team effort is unrelated to what we did here.

**Comment by zarubaf** [comment]
I would say we go for it :-) I will try to put in a good word for the changes in fpnew :-D

**Comment by JeanRochCoulon** [comment]
Hello @niwis    The CI is green (except for vcs-uvm teermination pb which I need to fix). I would be pleased to merge but as your PR is in "draft" mode, I cannot.

**Comment by JeanRochCoulon** [comment]
Today two common_cells are vendorized: one dedicated to fpu_new, and one for the rest of CVA6. But fpu_new common cells are not used. Switching to new fpu_new does it require to use other commencells for fpu_new ?

**Comment by niwis** [comment]
Hi @JeanRochCoulon, if I understood correctly, these changes should be merged into fpnew first and then bumped from there

**Comment by JeanRochCoulon** [comment]
No, it is more complex: common_cells is outside fpnew (we can regret it). So the update of fpnew should be coupled with the update of common_cells (I speak about common-cells related to fpnew, not the rest of cva6).
On the top of it, #1026 explains that only the cva6 common_cells is used by Flist, that's a bug.
Anyway, I see 2 possibilities: you update the fpnew common_cells and you solve the #1026 bug which is the best-in-class solution or you only update fpnew common_cells to align the two vendorized repositories.

**Comment by mp-17** [comment]
I opened the PR (https://github.com/openhwgroup/cvfpu/pull/78) before reading all the comments here. 
@JeanRochCoulon, I would merge the `vec` branch first in `fpnew` if the maintainers agree, as this should be orthogonal to the `common_cells` duplicate problem. 
Also, if this `fpnew` version bump is not introducing the `common_cells` problem, do you think we can bump `fpnew` anyway and then solve the `common_cells` duplicate issue with a separate and dedicated `fpenw` version bump?

**Comment by zarubaf** [comment]
We have [`v0.7.0`](https://github.com/openhwgroup/cvfpu/releases/tag/v0.7.0) ready to integrate. Do we need to update the `common_cells`, I don't think so, since it is backward compatible.

**Comment by JeanRochCoulon** [comment]
Thales CI is failed. Can you rebase your PR? I think it will help.

**Comment by zarubaf** [comment]
Hey @niwis, @JeanRochCoulon are we blocked on this? What exactly failed on the Thales CI?

**Comment by niwis** [comment]
@zarubaf this PR blocks #1024. However, this again is blocked by the broken `v0.7.0` release of CVFPU. AFAIK @lucabertaccini is still waiting for permission from the code owners to force-push to the CVFPU master branch (but nobody seems to be responsible?). I propose to re-vendor and rebase this PR once `v0.7.0` has been fixed and then have another look at the Thales CI.

**Comment by zarubaf** [comment]
Ah I didn't know the `cvfpu` is broken. Why is the release `v0.7.0` broken?

**Comment by lucabertaccini** [comment]
Hi @zarubaf, regarding the `cvfpu` release `v0.7.0`: the code base is fine but the history between `master` and `develop` got misaligned. I think solving this issue would ease future contributions.

**Comment by niwis** [comment]
@zarubaf @lucabertaccini thanks for handling this. As discussed separately, `v0.7.0` is stable and can be used here. I rebased this PR, let's wait for CI.

**Comment by zarubaf** [comment]
@JeanRochCoulon are we looking good on the CI?

**Comment by JeanRochCoulon** [comment]
No, the ASIC synthesis is down. I have just submitted a PR to pulp-platform:fpu-update to fix it. Please accept it to be able to replay the CI. It should be ok with this fix.

**Comment by niwis** [comment]
Done, thanks! let's see

**Comment by JeanRochCoulon** [comment]
Super !!     :-)

**Pull request merged**
