### PR TITLE
Mmu user manual

### PR DESCRIPTION
**Pull request by AngelaGonzalezMarino**
Update the “RISC-V Virtual Memory” section in the CVA6 user manual with Sv32, Sv39 and Sv39x4 information after MMU merge

### CODE REVIEW

**Review by jquevremont — APPROVED** [review]
LGTM. @fatimasaleem, can you double check?

**Comment by fatimasaleem** [comment]
As far as I know, we have not integrated the hypervisor extension in the CVA6, and the parameter `CVA6ConfigHExtEn` does not exist in the latest master. Shouldn't we add the hypervisor related stuff in the user manual when it actually in the core?

**Comment by jquevremont** [comment]
> As far as I know, we have not integrated the hypervisor extension in the CVA6, and the parameter `CVA6ConfigHExtEn` does not exist in the latest master. Shouldn't we add the hypervisor related stuff in the user manual when it actually in the core?

Thanks @fatimasaleem. We need to address the time until the hypervisor extension is merged.

I suggest to keep the text and add a note (that we'll remove when the hypervisor extension is merged). See https://github.com/planvtech/cva6/pull/42.

**Comment by fatimasaleem** [comment]
Sounds good!

**Review by fatimasaleem — APPROVED** [review]

**Pull request merged**
