### PR TITLE
Cva6 reorg

### PR DESCRIPTION
**Pull request by ASintzoff**
As discussed during 2021-09-07 meeting, @MikeOpenHWGroup has rebased the cva6_reorg branch on master and "code compiles and runs the RISCV compliance suite."

### CODE REVIEW

**Comment by sjthales** [comment]
Hello,

I just tried 'make fpga' command to generate bitsream of cv64a6 but it doesn't work.

It seems items in cva6/fpga should be in corev_apu/fpga.

In addition, cva6/src content should be placed into cva6/core directory.

Regards

**Comment by JeanRochCoulon** [comment]
We have used this cva6_reorg branch for two months. I am ok with the cva6_reorg RTL. The remaining work is to run the Thales continuous Integration on the rebase cva6_reorg branch to valid it. I let you know.

**Comment by zarubaf** [comment]
The failing FPGA build reported by @sjthales needs to be addressed before we can merge.

**Comment by ASintzoff** [comment]
> The failing FPGA build reported by @sjthales needs to be addressed before we can merge.

Fixed with https://github.com/openhwgroup/cva6/pull/726

Some files were created in the previous directories. I moved them.

**Comment by zarubaf** [comment]
Somehow the benchmarks failed. Can you reproduce this locally? Just re-triggered the CI to double check.

**Review by JeanRochCoulon — APPROVED** [review]
I have reviewed the code.
In parallel, I have seen that the github action #73 is PASS. 
So, it is OK on my side.

**Comment by zarubaf** [comment]
@all Are we good to merge? FPGA building okay?

**Comment by sjthales** [comment]
yes I generated both cv32a6 and cv64a6 on FPGA, it worked.

**Review by zarubaf — APPROVED** [review]
Lgtm

**Pull request merged**
