### PR TITLE
Add CV32A6 CSR specification in .rst and IP-XACT format

### PR DESCRIPTION
**Pull request by tolaszi**

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @tolaszi, thanks for this!   A couple of important points:
1. You will need to be covered by an [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) before this pull-request can be merged in.  (If you don't know what that is, send me a message via MatterMost and I can help you.
2. I believe these files should be located in `docs/design_spec/source`.

**Comment by tolaszi** [comment]
> Hi @tolaszi, thanks for this! A couple of important points:
> 
> 1. You will need to be covered by an [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) before this pull-request can be merged in.  (If you don't know what that is, send me a message via MatterMost and I can help you.
> 2. I believe these files should be located in `docs/design_spec/source`.

Hi @MikeOpenHWGroup - I believe both the ECA and the files' location is addressed now

**Comment by JeanRochCoulon** [comment]
Hello @tolaszi, Thank you for this very useful contribution. I would have two comments.
- Your PR has been done for a merge into openhwgroup:master, while it must be done to openhwgroup:cva6/dev
- Three columns are used to describe the"access type", "read behaviour" and "write behaviour". I think the information could be synthetized into only one column.
Cheers

**Comment by tolaszi** [comment]
> Hello @tolaszi, Thank you for this very useful contribution. I would have one comment.
> 
> * Three columns are used to describe the"access type", "read behaviour" and "write behaviour". I think the information could be synthetized into only one column.
>   Cheers

Hi @JeanRochCoulon - thanks for the feedback!. As for the read and write behaviors, they could potentially carry additional information. If a bitfield's behavior is read-to-clear, read-to-set, write-1-to-clear, write-1-to-set, etc., that shows up here. Apparently none of the current RISC-V CSRs have these behaviors so I agree that these columns seem redundant in this case. If you think this should be removed, I can add a check to the generator to only show these columns if any of the bitfields have these special behaviors.

It seems that your comment has been edited. Does it meant that the PR is ok on the CVA6/master branch?

**Comment by JeanRochCoulon** [comment]
Yes, the PR is ok with openhwgroup:master (I was confused with openhwgroup:core-v-verif repository)

**Comment by tolaszi** [comment]
I have done something very weird inadvertently to this PR. I wanted to update the PR with removing the read/write behavior as per Jean-Roch's comment. In the meantime the master moved ahead so I did the following:

- synced-up my local fork on the Github site
- locally on my laptop I did a `git pull` on the master branch
- switched to the `csr_specification` branch and did a `git rebase master`
- updated the `.rst` file and then did `git add`, `git commit` and then `git push origin csr_specification`
- the git push was rejected saying that the tip of my current branch is behind its remote counterpart

Now the latest commit on this PR looks like I want to merge master into the csr_specification branch. I am not sure what I did wrong and what triggered this last commit. Any help would be appreciated.

**Comment by JeanRochCoulon** [comment]
Hello @tolaszi

After rebasing master, some commits have been inserted before your personal commits. You have re-written the story. That's why you need to force the push by executing: "git push -f"

Three modifications are needed to insert the CSR in the readthedocs specification:
- the logo image should be moved from "source" into "images" directory, and the rst file calling the image should be updated
- The licence need to be added to the rst file + contributor name (if you like!). Refer to the FRONTEND.rst file as example.
- Add "CV32A6_CSR" into the index.rst file to add CSR chapter to the specification

To check whether the generation is ok, execute "make singlehtml" in the design_spec directory

I hope this will help
Cheers

**Comment by JeanRochCoulon** [comment]
You might need to install it:
pip3 install sphinxcontrib-svg2pdfconverter sphinx-github-changelog

**Comment by tolaszi** [comment]
Thanks for the help @JeanRochCoulon!

I may have made a royal mess of the commits but I _think_ the contents of the PR are now ok...

**Comment by JeanRochCoulon** [comment]
Thank you again @tolaszi for the high contribution. I will merge it and generate the master document (under readthedocs) which includes your chapter.

**Pull request merged**
