### PR TITLE
Update CVA6 Architecture overview Figure

### PR DESCRIPTION
**Pull request by YazanHussnain-10x**
This PR includes an updated version of the CVA6 Architecture Overview figure. The following changes have been made to the figure:

* The Re-aligner has been moved to the Frontend.
* Cache Subsystem (I$ and D$) have been moved outside the pipeline.
* Signals have been added in the ID, Issue, and Commit stages, with labels for clarification.
* An FPU has been added in the Execute stage.
* The Division logic has been highlighted inside the Mult module.

These updates were made with the intention of preserving the originality of the figure.

### CODE REVIEW

**Review by zarubaf — APPROVED** [review]
Looks amazing! Any chance we can also add the vector source file so that people can adapt it in case things change?

**Comment by fatimasaleem** [comment]
> Looks amazing! Any chance we can also add the vector source file so that people can adapt it in case things change?

Sure, we should add that, @YazanHussnain-10x can you add the source file in the same folder as well?

**Comment by YazanHussnain-10x** [comment]
I have added the vector file

**Comment by zarubaf** [comment]
Great that it is a `drawio` file. 
Small hint: You can save the drawio as `xyz.drawio.png` that results in a pseudo `png` that can be displayed in the documentation _and_ can be edited by drawio (so only one source file necessary). And I can also recommend the drawio vscode extension in case you don't know that one already :-)

**Comment by JeanRochCoulon** [comment]
Hi @YazanHussnain-10x 
Little feedbacks. The arrows are not all drawn with the same format: decoded instuction and valid for instance get the new format and signals from frontend are in old format. It would be great to uniformize the format.   Cheers

**Comment by YazanHussnain-10x** [comment]
@zarubaf, @JeanRochCoulon
Thanks for the suggestions and feedback. I have updated the figure and added the `.drawio.png` file.

**Pull request merged**
