### PR TITLE
Do not execute "regress" CI on PR

### PR DESCRIPTION
**Pull request by JeanRochCoulon**
To reduce the CI execution time on servers

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@cathales Can you approve ?

**Review by cathales — APPROVED** [review]
LGTM, I’m looking forward to two changes so that switching PR CI from *regress* to *dev* actually reduces latency for contributors:

1. an FPGA build optimization (eg: caching Vivado primitives)
2. triggering the Thales CI from a GitHub webhook on PR&master pushes instead of on schedule

**Comment by JeanRochCoulon** [comment]
Agree on the two improvement proposals

**Comment by cathales** [comment]
>     2. triggering the Thales CI from a GitHub webhook on PR&master pushes instead of on schedule

Update: this should be working from now 🚀 

@JeanRochCoulon should we create a task to investigate possible FPGA build duration optimizations?

**Comment by cathales** [comment]
It seems I’m not allowed to add tasks

**Comment by JeanRochCoulon** [comment]
Give me the texte you would like to add in kanban board, I will do the job

**Pull request merged**
