### PR TITLE
Add funding acknowledgement

### PR DESCRIPTION
**Pull request by jquevremont**
Add FRACTAL and TRISTAN funding acknowledgements. This section can later be completed with other EU or foreign projects.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@JeanRochCoulon I added ISOLDE

**Review by zarubaf — APPROVED** [review]
LGTM

**Comment by jquevremont** [comment]
> @JeanRochCoulon I added ISOLDE

I added ISOLDE grant number and related countries.

**Comment by JeanRochCoulon** [comment]
Should we add the same funding information in core-v-verif repository ?  As this repo will not modified by EU project contributions

**Comment by jquevremont** [comment]
> Should we add the same funding information in core-v-verif repository ? As this repo will be modified by EU project contributions

This makes sense, but you have to remove FRACTAL which was not about verification. You decide as the verification leader.

Then the text would become for core-v-verif:

```
Some contributions to CVA6 are supported by the TRISTAN and ISOLDE projects,
which have received funding from the Key Digital Technologies Joint Undertaking (KDT JU),
Austria, Belgium, Czechia, Finland, France, Germany, Italy, the Netherlands, Poland, Romania, Sweden, Switzerland, Spain and Turkey
under grant agreements 101095947 and 101112274.
The JU receives support from the European Union’s Horizon Europe research and innovation program.
![EU Logo](https://cloud.hipert.unimore.it/apps/files_sharing/publicpreview/pessWNfeqBfYi3o?x=1912&y=617&a=true&file=eu_logo.png&scalingup=0)
![KDT Logo](https://cloud.hipert.unimore.it/apps/files_sharing/publicpreview/yd7FgKisNgtLPTy?x=1912&y=617&a=true&file=kdt_logo.png&scalingup=0)   
```

**Pull request merged**
