### PR TITLE
Add user field between memory and caches

### PR DESCRIPTION
**Pull request by JeanRochCoulon**
2 commits: 
- fix the "dev dcache 32bits" commit: fix one assert activated when VCS is used. @sjthales, could you approve the fix ?
- Add user bits between memories and caches @Gchauvon

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@zarubaf I face a bug with Verilator, that's why I moved to 4.110 version, which is the version used in Thales CI. May I ask you to review this PR, I would need to have it merged on master to prepare the TC_SRAM pull request. Happy Easter Florian !

**Review by zarubaf — APPROVED** [review]
lgtm! Thanks!

**Comment by zarubaf** [comment]
Sorry to be late, thanks, and happy easter as well Jean Roch!

**Comment by JeanRochCoulon** [comment]
Fine! Thank you Florian

**Pull request merged**
