### PR TITLE
[Pmp] Parameter for PMP without MMU

### PR DESCRIPTION
**Pull request by CoralieAllioux**
First step for the PMP standalone: adding a dedicated parameter in config package and all configs.

It contributes to https://github.com/openhwgroup/cva6/issues/1447

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
Hello @CoralieAllioux 
The new parameter name tells the PMP instruction and data will be present when PmpPresent = 1. For instance:
- When MMU is present and PmpPresent = 0, we understand the PMP is not present
- When PmpPresent = 0, we understand the PMP instruction is not present whatever the MMU.
If it is the case, it would be great, do you confirm?  Otherwise, it could be confusing.

**Comment by CoralieAllioux** [comment]
Hello @JeanRochCoulon,
About the parameter, it only instantiates the PMP when the MMU is **not** present. Therefore the parameter PmpPresent is ignore in that case.
I could then rename it to PmpStandalonePresent or something similar to be more explicit. Would it be better for you?

**Comment by JeanRochCoulon** [comment]
This new parameter allows to disable the PMP _data_ when MMU not present and PmpPresent=0. To me this configuration does not need to be supported: this configuration is not compliant to RISC-V and I do not know a CVA6 user pleased to use it so far (maybe youself ?).

**Comment by CoralieAllioux** [comment]
I am not sure to understand your last comment. _PmpStandalonePresent_ was a suggestion to **rename** _PmpPresent_ if not explicit enough. This is not a new parameter

Here the possible configuration we're proposing:
- **MmuPresent=0 and PmpPresent=0:** nothing changes
- **MmuPresent=1 and PmpPresent=0:** nothing changes
- **MmuPresent=1 and PmpPresent=1:** nothing changes
- **MmuPresent=0 and PmpPresent=1:** here a pmp data and a pmp instruction are inserted, working without mmu

**Comment by JeanRochCoulon** [comment]
RISC-V specification tells that PMP is optional. But in CVA6, PMP regions are always 16.
To be compliant PMP data and instruction shall be supported. It is not the case Today when MMU is not present.
Your modification will make CVA6 compliant to RISCV when MMU is not present.

**Comment by CoralieAllioux** [comment]
Oh, so you're telling MmuPresent=0 is sufficient? If so, PmpPresent is not necessary... and the PR is not needed anymore

**Comment by CoralieAllioux** [comment]
Sorry for the missunderstanding. Then I cancel the PR.

**Pull request closed without merging**
