### PR TITLE
[Xcelium support] Remove void from DPI definition

### PR DESCRIPTION
**Pull request by CoralieAllioux**
This PR is related to the one done on core-v-verif with the same subject: https://github.com/openhwgroup/core-v-verif/pull/2366

Since the definition of the function `read_section_sv` has been updated in core-v-verif, its import needs to be updated in cva6. It also includes the hash update for core-v-verif submodule.

This has been check with VCS 2021.09: the behavior is the same than previous on our side. @MarioOpenHWGroup , can you give your feedback?

### CODE REVIEW

**Comment by MarioOpenHWGroup** [comment]
Looks good :+1:

**Comment by JeanRochCoulon** [comment]
Ouf, the parametrization is over. I suggest you to rebase your PR. The dashboard will provide you the logs of the failed simulation, if any (it is a new feature introduced recently). Good luck.

**Comment by CoralieAllioux** [comment]
Thank you Jean-Roch for updating the dashboard content :)
It seems this time the run is successful. However, the link given is associated to a failed run: the time is the one of the previous failed run.
Could you check it?

**Comment by JeanRochCoulon** [comment]
The server is down. We are fixing it.

**Comment by JeanRochCoulon** [comment]
Hello @CoralieAllioux   The PR has been closed, why ?

**Comment by CoralieAllioux** [comment]
Hello @JeanRochCoulon , the organization is changing authorization policy on boschglobal. It seems that our work is now private... They are in the recovery process, I'll let you know when it is fixed.

**Comment by CoralieAllioux** [comment]
Hi again @JeanRochCoulon, boschglobal recovered. I have no clue on how to open the PR again. Do I need to create another one? Or can you change the status to open?

**Comment by JeanRochCoulon** [comment]
ouf !

**Pull request merged**
