### PR TITLE
GSoC project: Enhancing OpenPiton+Ariane With a High-Performance Data Cache

### PR DESCRIPTION
**Pull request by AileonN**
This pull request is a draft for a future pull request which will integrate properly the addition of the HPDC to be compatible with OpenPiton

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
Hello @AileonN   As you can imagine, we cannot review, neither review your PR until it is not rebased. May I ask you to rebase ?

**Comment by AileonN** [comment]
> Hello @AileonN As you can imagine, we cannot review, neither review your PR until it is not rebased. May I ask you to rebase ?

Hello! Yes, I know :) I made a PR draft instead of a normal PR for that reason. In the following weeks, I will work on the rebase.

**Comment by JeanRochCoulon** [comment]
No problem, take your time !!  In that case, I will close the PR. You will be able to re-open it and relaunch the CIs when needed.

**Comment by Jbalkind** [comment]
Jean-Roch can you please reopen this? This is for Google Summer of Code.

**Pull request closed without merging**
