### PR TITLE
Introduce CV32A60X as first release

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
As discuss on [MatterMost](https://mattermost.openhwgroup.org/all-users/pl/inbaedgq3fgyf8sum9d3z7uozc), here is  proposed change to the requirements spec to introduce the initial configuration of the CVA6.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
Hi Mike, it looks fine to me !   Could you just replace sv39 by sv32 for MMU, when we are in 32bits, sv is lower than 32

**Review by JeanRochCoulon — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
> Hi Mike, it looks fine to me ! Could you just replace sv39 by sv32 for MMU, when we are in 32bits, sv is lower than 32

Done.  Thanks for the catch.

**Review by jquevremont — COMMENTED** [review]
The way to present configurations is excellent.
Pedantic: CVFPU is not defined. I suggest to either define it at the end of the document or revert to FPU. (not a blocking comment)

**Review by jquevremont — APPROVED** [review]
LGTM

**Review by JeanRochCoulon — APPROVED** [review]

**Pull request merged**
