### PR TITLE
Clarify scope of Verilator model

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
Hi @JeanRochCoulon, this is a very simple pull-request just to test your new powers as a CORE-V Committer.

Signed-off-by: Mike Thompson <mike@openhwgroup.org>

### CODE REVIEW

**Review by JeanRochCoulon — APPROVED** [review]

**Review by zarubaf — APPROVED** [review]

**Comment by JeanRochCoulon** [comment]
@MikeOpenHWGroup As told, my new power works on PR submitted after my right attribution. But as this PR has been sumitted before, it does not work. So I cannot merge this PR. You have to do it !   Thanks !

**Comment by zarubaf** [comment]
@JeanRochCoulon Are your powers working now? Or shall I merge?

**Comment by JeanRochCoulon** [comment]
No, I have no powers on this PR, maybe because it has been pulled before the power attributions. So, you can merge.

**Comment by zarubaf** [comment]
Hm, I was under the impression that your rights should apply to all PRs (independent of creation date). Can you please check whether you can merge a new PR and come back to me about it? 

I honestly don't get the user settings for the repo. Technically we are in the same permission group (comitters with write permissions) but I can also adjust all admin repo settings. Not sure how Eclipse managed that :-)

**Comment by DBees** [comment]
Membership in the Eclipse-managed Committer team gives you write permission on CORE-V Cores repos. 
Separately, OpenHW staff also have admin rights on all OpenHW repos.

**Comment by zarubaf** [comment]
@DBees its clear what the intentions are but apparently this does clarify how/if (apparently not) it is technically implemented. As an intermediate step I will add @JeanRochCoulon to the repo manually

**Comment by zarubaf** [comment]
We've debugged it. Apparently, it was the branch protection rule for `master` which prevented people with `write` permissions to push to the branch. Solution was to whitelist `corev-comitters` to be able to push to `master`. @JeanRochCoulon  we can finally close this :-D

**Pull request merged**
