### PR TITLE
[fix] fix openpiton simulation flist with HEAD

### PR DESCRIPTION
**Pull request by tianrui-wei**
Signed-off-by: Tianrui Wei <tianrui-wei@outlook.com>

### CODE REVIEW

**Comment by zarubaf** [comment]
LGTM, can you please sign the Eclipse ECA so that the CI passes?

**Review by zarubaf — APPROVED** [review]

**Comment by tianrui-wei** [comment]
Will do.
I'll also add another import fix for ariane_verilog_wrap in a miniute

**Comment by tianrui-wei** [comment]
@zarubaf Please review the PR again:P I've updated the necessary imports for `ariane_verilog_wrap`. This is required after global imports were disabled, which `ariane_verilog_wrap` previously depended on.

**Review by zarubaf — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
