### PR TITLE
Adding configuration-specific CSR doc

### PR DESCRIPTION
**Pull request by jquevremont**
First attempt to add configuration-specific CSR lists and descriptions in the user manual.
First attempt to point to a file in another subdirectory (common between user manual and design document). I think we need to PR to test if it creates the expected result in ReadTheDocs.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
To test the readthedoc generation, you can execute "make singlehtlm" after cloning repo in linux env.

**Comment by jquevremont** [comment]
> To test the readthedoc generation, you can execute "make singlehtml" after cloning repo in linux env.

Thanks for the hint. The ``include`` from another directory is operational.

@JeanRochCoulon, I need your help to proceed further:
- There is no csr_list.rst in [csr-from-ip-xact/cv32a60ax](https://github.com/openhwgroup/cva6/tree/master/docs/csr-from-ip-xact/cv32a60ax)
- Could you change the titles to be more specific in the .rst files as this directly appears in the generated doc? E.g. "**CV32A60X** CSR descriptions" instead of "REGISTERS CSR **CV32A6**" in [csr-from-ip-xact/cv32a60x/csr.rst](https://github.com/openhwgroup/cva6/blob/master/docs/csr-from-ip-xact/cv32a60x/csr.rst)

As these are generated files, I do not edit them.

**Comment by jquevremont** [comment]
>  There is no csr_list.rst in [csr-from-ip-xact/cv32a60ax](https://github.com/openhwgroup/cva6/tree/master/docs/csr-from-ip-xact/cv32a60ax)

Also sphinx returns ``WARNING: toctree contains reference to document 'CSR_CV32A60AX' that doesn't have a title: non link will be generated``, so I have added a placeholder instead of this file, while this is fixed.

> Could you change the titles to be more specific in the .rst files as they directly appear in the generated doc? E.g. "**CV32A60X** CSR descriptions" instead of "REGISTERS CSR **CV32A6**" in [csr-from-ip-xact/cv32a60x/csr.rst](https://github.com/openhwgroup/cva6/blob/master/docs/csr-from-ip-xact/cv32a60x/csr.rst)

I could find a workaround in ``index.rst`` with ``toctree`` syntax.

FYI @JeanRochCoulon, sphinx returns many such non-blocking warnings, that you might consider fixing in the CSR document generator:

```
REGISTERS CSR CV32A6
===================
../csr-from-ip-xact/cv32a60x/csr.rst:11: WARNING: Title underline too short.

Unimplemented CSR accessing generates an illegal instruction exception.
--------------------------
../csr-from-ip-xact/cv32a60x/csr.rst:13: WARNING: Title underline too short.
```

and

```
MSTATUS:Machine Status Register
--------------------------
../csr-from-ip-xact/cv32a60x/csr.rst:38: WARNING: Inline literal start-string without end-string.
../csr-from-ip-xact/cv32a60x/csr.rst:50: WARNING: Inline literal start-string without end-string.
../csr-from-ip-xact/cv32a60x/csr.rst:56: WARNING: Inline literal start-string without end-string.
```

**Comment by JeanRochCoulon** [comment]
Sorry for the delay !    I merge

**Pull request merged**
