### PR TITLE
Fix event tracing on more commit ports.

### PR DESCRIPTION
**Pull request by luca-valente**
With two (or more) commit ports, the `for (int unsigned j = 0; j < NR_COMMIT_PORTS; j++) if (commit_ack_i[j]) events[i] = commit_instr_i[j].fu == LOAD;//Load accesses` does not set `events[i]=1'b1` if there are two committed instructions (`commit_ack_i=2'b11`) and only one of them is a load, while it should.
The same is true for the other events.
This commit explicitly checks on each commit port and then checks that at least one committed the event being monitored.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@TulikaSi

**Comment by TulikaSi** [comment]
Hi @luca-valente 
I see that few tests have failed during the checks.
Is it related to the modifications done? Are you working on it?

**Comment by JeanRochCoulon** [comment]
Hello @luca-valente    Thank you for your contribution. The Thales CI is green, that is a great step forward to get your PR merged on the master line. As you can see some checks are not successful. To become contributor, can you sign the eclipsefdn/eca agreement ?

**Comment by luca-valente** [comment]
Hello, I created an account on the Eclipse foundation and signed the ECA.
If I verify the ECA it says `There is a valid ECA on file for ...`
Is this sufficient?

**Comment by JeanRochCoulon** [comment]
@luca-valente    As there is no more the eclipsefdn/eca error executing the Github Actions CI, so that's solved. You can become a CVA6 contributor. Let's wait for the Github CI result

**Comment by TulikaSi** [comment]
> Hi @luca-valente @JeanRochCoulon Thank you @luca-valente for the commit :) In the first glance the changes looks good to me but I would just like to compare few things before giving a final thumbs up.

Hi @JeanRochCoulon 
We can merge the changes to the performance counter. Thank you @luca-valente for bringing up the corner case.

**Comment by JeanRochCoulon** [comment]
Bender test is failed, I close then reopened to rerun the test

**Comment by JeanRochCoulon** [comment]
Thanks @luca-valente and @TulikaSi for your contribution !!

**Pull request merged**
