### PR TITLE
Fix PMPCFG csr read for 32bit configuration

### LINKED ISSUE #733: PMP Configuration Registers pmpcgf1 and pmpcfg3 for CV32A6 is not present for CSR Read
As per specification for 32 Bit CPU we should have CSR_PMPCFG0, CSR_PMPCFG1, CSR_PMPCFG2 and CSR_PMPCFG3. How ever for 64 bit CPU, it requires only CSR_PMPCFG0 and CSR_PMPCFG2 [ For CSR Read this is present in RTL].
For CSR Read CSR_PMPCFG1 and CSR_PMPCFG3 is not present which is required for 32 Bit CPU.

### PR DESCRIPTION
**Pull request by Moschn**
Fixes #733

### CODE REVIEW

**Comment by zarubaf** [comment]
You are the best, thanks @Moschn! @JeanRochCoulon can you confirm that this solves your issue, please?

**Review by zarubaf — CHANGES_REQUESTED** [review]
👍

**Comment by Moschn** [comment]
I cannot reproduce the CI failure locally. `rsort.riscv` runs on my machine.

**Comment by nathpranay** [comment]
Hi 
I feel for XLEN=32, CSR_PMPCFG1 and CSR_PMPCFG2 shall give same i.e. pmpcfg_q[7:4], but CSR_PMPCFG2 should have pmpcfg_q[11:8]
                riscv::CSR_PMPCFG0:          csr_rdata = pmpcfg_q[riscv::XLEN/8-1:0];
                riscv::CSR_PMPCFG1:          if (riscv::XLEN == 32) csr_rdata = pmpcfg_q[7:4]; else read_access_exception = 1'b1;
                riscv::CSR_PMPCFG2:          csr_rdata = pmpcfg_q[riscv::XLEN/8*2-1:riscv::XLEN/8];
                riscv::CSR_PMPCFG3:          if (riscv::XLEN == 32) csr_rdata = pmpcfg_q[15:12]; else read_access_exception = 1'b1;

**Comment by Moschn** [comment]
Yes, you are correct. I believe I fixed it now.

**Comment by zarubaf** [comment]
@nathpranay can you confirm pls?

**Comment by nathpranay** [comment]
@zarubaf , this looks fine. I am sorry, missed to reply.

**Pull request merged**
