### PR TITLE
Disable MISA WE in Reference Model

### PR DESCRIPTION
**Pull request by MarioOpenHWGroup**
- Disabling MISA WE as cva6 does not allow writes
- Add YAML report for all the tests

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@zchamski Can you approve ?

**Comment by AyoubJalali** [comment]
I don't know why but I need to give the cva6.py the misa_we_enabled to get spike work !!

**Comment by JeanRochCoulon** [comment]
MISA is read only. I do not understand why in Spike MISA need to be write-able !?
image

**Comment by zchamski** [comment]
> I don't know why but I need to give the cva6.py the misa_we_enabled to get spike work !!

The `misa_we_enable` parameter (with value 'true') *enables* the control of the writability of MISA via the parameter `misa_we`. 
If `misa_we_enable` is left at `false`, the default behavior of Spike remains in effect, which is to keep MISA extension bits `MAFDQCHV` writable (https://github.com/openhwgroup/core-v-verif/blob/master/vendor/riscv/riscv-isa-sim/riscv/csrs.cc#L613)

**Review by zchamski — APPROVED** [review]
LGTM

**Pull request merged**
