### PR TITLE
[Pmp] Verif plan TXT

### PR DESCRIPTION
**Pull request by CoralieAllioux**
This PR aims at resolving task https://github.com/openhwgroup/cva6/issues/1447

Here's a first version of the Verification Plan of PMP, in txt format.
It is split in 2 files:
- verif/docs/VerifPlans/PMP/pmp_verif_plan.txt
- verif/docs/VerifPlans/PMP/pmp_verif_plan_features.txt

VPTool format is undergoing on our side.
We'd like to share already the content to get first feedbacks.

### CODE REVIEW

**Comment by jquevremont** [comment]
Hi @JeanRochCoulon, can you give a look?

**Comment by OlivierBetschi** [comment]
Added to this pull request are some PMP tests along with the Verif Plan integrated in VP_TOOL. Weird that CI is failing as no RTL has been updated and the PMP tests are not integrated into the regression scripts

**Comment by OlivierBetschi** [comment]
The PMP updated has been merged ( https://github.com/openhwgroup/cva6/pull/2528). @ASintzoff @JeanRochCoulon does the VP_TOOL update and provided tests look ok to you ?
I have no idea why the ECA check is failing as I have signed the agreement. It seems to come from the latest merge of master.

**Comment by JeanRochCoulon** [comment]
This PR modifies 50k lines: too much. Maybe a rebase issue.
This PR should execute tests on the new RTL with extracted PMP. Let's see the results !

**Comment by JeanRochCoulon** [comment]
I found. This PR is related to master_when_no_mmu, while it should be master.

**Pull request closed without merging**
