### PR TITLE
axi: Upgrade to v0.39.1

### PR DESCRIPTION
**Pull request by niwis**
Upgrade the AXI dependency from v0.31.0 to v0.39.1. Note that most changes are within the vendored AXI repository. See the [changelog of the AXI repo](https://github.com/pulp-platform/axi/blob/master/CHANGELOG.md) for details.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
The update introduces a regression in term of cycles on Coremark.

**Comment by JeanRochCoulon** [comment]
The coremark performance is fixed. But now the Linux boot is failed, which is less fun to debug.

**Comment by niwis** [comment]
That's too bad. I will give it a try

**Comment by JeanRochCoulon** [comment]
The common trick to found out the error is to compare the FPGA builds with and without the modification.

**Comment by JeanRochCoulon** [comment]
@niwis, I close the issue as fiw has not been found

**Pull request closed without merging**
