### PR TITLE
Feat: add add cva6_hpdcache_icache_if_adapter (supports the simplified icache kill mechanism)

### PR DESCRIPTION
**Pull request by takeshiho0531**
- I will discard PR #2238  and work on it here.
  - changed base branch from `master` to `feature/interconnect`
- The parts highlighted in light pink are the ones we want to implement in this PR.
port adapter

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
Nice to see you are contributing for feature/interconnect branch !

@yanicasa How to check the PR with Thales CI before merging ?

**Comment by yanicasa** [comment]
LGTM, 
@takeshiho0531 are you considering adding a way to select hpicache instead of icache per configuration? Something similar to caches might be interesting!

**Comment by JeanRochCoulon** [comment]
@takeshiho0531   On our side, we are ready to merge. The PR is in Draft mode, what is your plan: would you like to merge now or later ?

**Comment by takeshiho0531** [comment]
@JeanRochCoulon 
Sorry for the late reply.
For now, I will merge this! (If there are any parts that need to be fixed in future development, we will address them at that time.)

**Comment by takeshiho0531** [comment]
@yanicasa 
Thank you :)
I'd like to make it possible to select between hpicache and icache depending on the configurations.

**Pull request merged**
