### PR TITLE
Add smoke-tests and fpga logs on dashboard

### PR DESCRIPTION
**Pull request by valentinThomazic**
Add smoke-tests and FPGA logs recollection in order to make them available on the Thales CI Dashboard.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@AngelaGonzalezMarino This PR made by @valentinThomazic will help you to debug the MMU. Just rebase. You can access to the log file of the smoke_tests from the Dashboard.

**Comment by JeanRochCoulon** [comment]
This fetaure can help you  @MarioOpenHWGroup

**Comment by MarioOpenHWGroup** [comment]
This will help me for sure :smile:

**Comment by AngelaGonzalezMarino** [comment]
Great contribution @valentinThomazic ! I have been able to solve the problems reported by VCS :)

**Comment by valentinThomazic** [comment]
Glad to hear that @AngelaGonzalezMarino :) :

**Pull request merged**
