### PR TITLE
axi Specification: Modify the AXI memory interface specification

### PR DESCRIPTION
**Pull request by AEzzejjari**
Modify AXI interface specification by adding constraint that are not supported by CVA6

### CODE REVIEW

**Comment by jquevremont** [comment]
@JeanRochCoulon, can you merge if you agree?

**Comment by JeanRochCoulon** [comment]
@ludovicpion This is our AXI specification. It would be useful if you could review it. You have the AXI knowledge, that could help us to improve the quality of the specification.  Thanks

**Comment by JeanRochCoulon** [comment]
@ludovicpion @AEzzejjari  Thsi PR is open since a lon,g time, what is the status of this PR ?

**Comment by AEzzejjari** [comment]
@JeanRochCoulon I think we can merge this PR. We didn't receive any feedback from CEA about the specification in their last review.

**Comment by JeanRochCoulon** [comment]
@ludovicpion  Any feedbacks ?

**Pull request merged**
