### PR TITLE
ADD RISC-V CONFIG SOFTWARE

### PR DESCRIPTION
**Pull request by AbdessamiiOukalrazqou**
This software takes a Risc -V Config Yaml description of CSR Registers, and generates ReStructuredText documents and Mardown Documents for CSR Registers and ISA Extensions. In the example/tb directory there is an example of how to generate the packages

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@AbdessamiiOukalrazqou   can you sign the eclipsefdn/eca agreement ?

**Comment by ASintzoff** [comment]
Could you format the Python files with black?

**Comment by JeanRochCoulon** [comment]
As we are in open source, the files need to be with header indicating it, also if they are generated, can you add headers ?

**Comment by AbdessamiiOukalrazqou** [comment]
we will take care of reformatting files with black and Headers

**Pull request closed without merging**
