### PR TITLE
ASID 16-BIT implementation

### PR DESCRIPTION
**Pull request by marcosabatano**
Signed-off-by: Marco Sabatano <marco.sabatano@hensoldt-cyber.com>

### CODE REVIEW

**Comment by zarubaf** [comment]
Can you please re-base on the latest master?

**Comment by marcosabatano** [comment]
rebase done

**Comment by marcosabatano** [comment]
Looks like with latest commits picked up from the rebase, new passing parameter style is used, the code is not yet up to date to use them.

**Comment by zarubaf** [comment]
Thanks, is it good to go from your side?

**Comment by marcosabatano** [comment]
Hi Florian, yes from my PoV is fine.

**Pull request merged**
