### PR TITLE
Define AXI as cva6 input parameters

### PR DESCRIPTION
**Pull request by JeanRochCoulon**
Previously a part of AXI was defined in packages, now it is defined as cva6 input parameters

Signed-off-by: Jean-Roch Coulon <jean-roch.coulon@thalesgroup.com>

### CODE REVIEW

**Comment by Jbalkind** [comment]
Can you please incorporate the changes I provided in my PR for the previous "noc" patch on the Thales fork?

**Comment by JeanRochCoulon** [comment]
Hello @Jbalkind     I do not find out your changes in https://github.com/ThalesSiliconSecurity. Can you provide an URL ?

**Comment by Jbalkind** [comment]
You closed the issue when you deleted the previous branch: https://github.com/ThalesSiliconSecurity/cva6/pull/1

**Review by zarubaf — APPROVED** [review]
Awesome, much cleaner now. Thanks!

**Pull request merged**
