### PR TITLE
[CSR] Fix bits when RVS and RVU not available

### PR DESCRIPTION
**Pull request by MarioOpenHWGroup**
Disable some bits when RVU or RVS not present

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@MarioOpenHWGroup @zchamski   Is it good time to rebase and merge it ?

**Comment by zchamski** [comment]
> @MarioOpenHWGroup @zchamski Is it good time to rebase and merge it ?

IMHO definitely yes.

**Comment by JeanRochCoulon** [comment]
@zchamski    Do you know which are the github issues which are closed by this fix ?

**Comment by zchamski** [comment]
> @zchamski Do you know which are the github issues which are closed by this fix ?

I need to look these up...

**Pull request merged**
