### PR TITLE
Add Variant into CVA6 parameter

### PR DESCRIPTION
**Pull request by JeanRochCoulon**
Signed-off-by: Jean-Roch Coulon <jean-roch.coulon@thalesgroup.com>

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
Hello @zarubaf @Jbalkind 
This PR is not yet functional, but I would like to share it with you. As you can see the CVA6Cfg is composed of parameters related to User configuration, and "extended" which corresponds to parameters calculated from User parameters.
Cheers

**Comment by Jbalkind** [comment]
This looks very exciting! Thank you for taking the time to chase this :)

**Comment by zarubaf** [comment]
Totally approve of this change!

**Comment by JeanRochCoulon** [comment]
@zarubaf @Jbalkind  Thank you for your enthusiasm. I will fix the PR to have everything pass at my holidays come back.

**Comment by JeanRochCoulon** [comment]
@zarubaf the PR has been modified to :
- fix the FPGA issue you get in your #1321 PR. IsRVFI has been extracted from CVA6Cfg to allow a different configuration in FPGA case.
- add the config_pkg to avoid duplication of CVA6Cfg type definition.

Can you approve and merge ?!?   Then #1321 merge should be easier (I hope)

**Review by zarubaf — APPROVED** [review]
Awesome

**Pull request merged**
