### PR TITLE
cva6_icache: Allow one outstanding killed miss

### PR DESCRIPTION
**Pull request by colluca**
This PR relates to the following behaviour.

The I$ can receive a speculative request from the instruction fetch unit (e.g. upon a branch). If this instruction is not in the cache we will incur a miss and a refill request will be issued to the memory. If, when the branch is resolved, the speculated instruction is killed, the refill request will be killed (i.e. the speculated instruction will never be loaded into the cache). Despite being killed, the I$ still waits on the request from memory to be back, stalling all other operation. This implies that even with a hot cache, we can still experience cache miss stalls on speculated instructions which will never enter the cache, and hence the cache will never truely be "hot" (in this sense, speculated instructions should be considered part of the working set).

This PR attempts to improve performance in this condition by handling up to one killed refill request asynchronously. A speculated miss will only induce a stall if another miss occurs before the killed refill returns from memory.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
@colluca can you rebase to solve the conflicts ?

**Comment by JeanRochCoulon** [comment]
Hello @colluca   Since 4 weeks the PR is open... To be able to help in fixing the current issues, can you rebase the PR ?

**Comment by colluca** [comment]
Hi @JeanRochCoulon, sorry I'm very busy at the moment and could only have a deep look at it after mid November, but I have rebased it as requested.

**Comment by JeanRochCoulon** [comment]
Ok, I will relaunch the Thales CI

**Comment by cathales** [comment]
Hello @colluca,
Do you need help to reproduce the issue reported by CI in your local environment?

**Comment by colluca** [comment]
@cathales That would be great, now I have time to get back to this work item :)

**Comment by JeanRochCoulon** [comment]
Hello @colluca     Do you have time to look at it ?

**Comment by JeanRochCoulon** [comment]
As this PR cannot be merged. I close it and open a github issue to log the issue #1785.

**Pull request closed without merging**
