### PR TITLE
Fix VCD generation from Verilator model

### PR DESCRIPTION
**Pull request by pcotret**
This pull request is an answer to my issue described at https://github.com/openhwgroup/cva6/issues/1340
Quick comments:
- I've removed the `-j${NUM_JOBS}` in Verilator generation as it basically shut down my VM (8 cores...).
- Modifications in Readme: I've tested with Verilator v4.110. I assume it should be compatible with other versions as well.

### CODE REVIEW

**Comment by JeanRochCoulon** [comment]
Hello @pcotret
Nice to get your contribution
The CI is currently red. I think it is needed to rebase your PR to pass the CI. Can you ?

**Comment by pcotret** [comment]
I'll try it!

**Comment by pcotret** [comment]
CI goes red again...
Commit 1db42ee8da0b10a96acdb2cd5f18b9d8761bc381 gives also a red CI, not for all same steps. We may have a double effect.

**Comment by JeanRochCoulon** [comment]
I suspect a misfunctionality of the CI. I relaunched.

**Comment by JeanRochCoulon** [comment]
Now it is GREEEEN. Thanks for the contribution. I merge.
Have fun with CVA6 !

**Pull request merged**
